import Link from "next/link";

export const metadata = {
  title: "Terms of Service - KidsClaw",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="bg-white border-b border-gray-200 sticky top-0 z-50">
        <div className="flex items-center justify-between px-6 py-3 max-w-4xl mx-auto">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 bg-[#e60012] rounded-lg flex items-center justify-center text-white font-extrabold text-xs">
              KC
            </div>
            <span className="text-lg font-extrabold text-[#2d2d2d]">KidsClaw</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-extrabold text-[#2d2d2d] mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-10">Last updated: March 18, 2026</p>

        <div className="prose prose-sm prose-gray max-w-none space-y-8 text-[#2d2d2d]">
          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using KidsClaw (&ldquo;the Service&rdquo;), operated by Last Myle LLC (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service. By creating an account or allowing your children to use the Service, you represent that you are at least 18 years old and have the legal authority to agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed">
              KidsClaw provides AI-powered educational games for children. The Service includes web-based game interfaces, server provisioning, and related features. The Service is provided on an &ldquo;as available&rdquo; basis and may be modified, suspended, or discontinued at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#e60012]">3. USE AT YOUR OWN RISK</h2>
            <p className="text-gray-700 leading-relaxed font-semibold">
              YOUR USE OF KIDSCLAW IS ENTIRELY AT YOUR OWN RISK. The Service is provided &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
            </p>
            <p className="text-gray-700 leading-relaxed">
              We do not warrant that the Service will be uninterrupted, error-free, secure, or free of viruses or other harmful components. We do not warrant the accuracy, completeness, or reliability of any content generated by the AI systems used within the Service. AI-generated content may contain errors, inaccuracies, or inappropriate material despite our efforts to prevent this.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#e60012]">4. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed font-semibold">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LAST MYLE LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-1">
              <li>Your use of or inability to use the Service</li>
              <li>Any content generated by AI systems within the Service</li>
              <li>Any interactions your children have with the Service</li>
              <li>Unauthorized access to or alteration of your data</li>
              <li>Any third-party conduct on the Service</li>
              <li>Server downtime, data loss, or infrastructure failures</li>
              <li>Any other matter relating to the Service</li>
            </ul>
            <p className="text-gray-700 leading-relaxed font-semibold mt-4">
              IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU EXCEED THE AMOUNT YOU HAVE PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR TEN DOLLARS ($10.00), WHICHEVER IS GREATER.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#e60012]">5. No Warranty</h2>
            <p className="text-gray-700 leading-relaxed font-semibold">
              WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p>
            <p className="text-gray-700 leading-relaxed">
              We make no warranty that the Service will meet your requirements or expectations, that any content will be appropriate for children of any age, or that the educational content is accurate or complete. Parents and guardians are solely responsible for supervising their children&rsquo;s use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">6. Parental Responsibility</h2>
            <p className="text-gray-700 leading-relaxed">
              You acknowledge and agree that you are solely responsible for your children&rsquo;s use of the Service. You are responsible for monitoring your children&rsquo;s interactions, reviewing content they encounter, and determining whether the Service is appropriate for your children. We are not a substitute for parental supervision.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">7. AI-Generated Content</h2>
            <p className="text-gray-700 leading-relaxed">
              The Service uses artificial intelligence to generate educational game content and responses. AI-generated content may occasionally be inaccurate, misleading, or inappropriate despite our safety measures. We do not guarantee the accuracy, safety, or appropriateness of any AI-generated content. You acknowledge that AI systems can produce unexpected outputs and agree to use the Service with this understanding.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">8. Infrastructure and Data</h2>
            <p className="text-gray-700 leading-relaxed">
              The Service provisions cloud server infrastructure on your behalf. We are not responsible for any costs, damages, or losses arising from infrastructure provisioning, server failures, data loss, or security breaches. You are responsible for managing your account and shutting down servers when not in use. We reserve the right to terminate or suspend servers at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">9. Indemnification</h2>
            <p className="text-gray-700 leading-relaxed">
              You agree to indemnify, defend, and hold harmless Last Myle LLC and its officers, directors, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys&rsquo; fees) arising from your use of the Service, your violation of these Terms, or your violation of any rights of a third party.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">10. Termination</h2>
            <p className="text-gray-700 leading-relaxed">
              We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will immediately cease. All provisions of these Terms which by their nature should survive termination shall survive.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">11. Changes to Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Your continued use of the Service after changes are posted constitutes your acceptance of the modified Terms. We encourage you to review these Terms periodically.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">12. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the State of Washington, without regard to its conflict of law provisions. Any disputes arising from these Terms or the Service shall be resolved exclusively in the courts located in San Francisco County, California.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-[#2d2d2d]">13. Contact</h2>
            <p className="text-gray-700 leading-relaxed">
              If you have any questions about these Terms, please contact us at support@kidsclaw.club.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-[#2d2d2d] text-white py-8 mt-16">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <p className="text-white/50 text-sm">
            Copyright &copy; 2026 Last Myle LLC. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
